''''
SetupBuilderTest.py

Created on: 20.08.2023
    Author: SeaPlusPro
   License: CC0 1.0 Universal
'''
import re
import json
import unittest
import form2linux
import Builder
from base import StringUtils
from base import FileHelper

def inDebug(): return False

class InstallF2LTest(unittest.TestCase):

    def testExampleStandardHost(self):
        if inDebug(): return
        fnOutput = FileHelper.tempFile('install-std-host.example', 'unittest')
        form2linux.main(['form2linux', 'install', 'example-standard-host', f'--file={fnOutput}'])
        lines = StringUtils.fromFile(fnOutput)
        json.loads(lines)
        self.assertTrue(lines.find('any@gmx.de') >= 0)

    def testStandardHost(self):
        if inDebug(): return
        fnForm = FileHelper.tempFile('stdusers.json', 'unittest')
        StringUtils.toFile(fnForm, '''{
  "Variables": {
    "EMAIL": "any@gmx.de"
  },
  "ConfigurationDirectory": "/tmp/unittest/install",
  "Packages": [
      "htop",
      "ssmtp shareutils"
  ],
  "Ssmtp": {
      "Directory": "/tmp/ssmtp",
      "Sender": "%(EMAIL)",
      "!Code": "TopSecret",
      "MailHub": "mail.gmx.net:587",
      "Users": "root,jonny",
      "Comment": "StartTLS or TLS",
      "Mode": "StartTLS"
  }
}
''')
        form2linux.main(['form2linux', '-v', 'install', 'standard-host', fnForm])
        logger = Builder.BuilderStatus.lastLogger()
        lines = re.sub(r'\.\d+', '.X', '\n'.join(logger.getMessages())) + '\n'
        self.assertEquals(lines, '''sudo apt-get -y install htop ssmtp shareutils
sudo mv -v /tmp/ssmtp/ssmtp.conf /tmp/ssmtp/ssmtp.conf.X
sudo mv -v /tmp/ssmtp/revaliases /tmp/ssmtp/revaliases.X
''')
        lines = StringUtils.fromFile('/tmp/ssmtp/revaliases')
        self.assertEquals(lines, '''root:any@gmx.de:mail.gmx.net:587
jonny:any@gmx.de:mail.gmx.net:587
''')
        lines = StringUtils.fromFile('/tmp/ssmtp/ssmtp.conf')
        self.assertEquals(lines, '''# generated by Form2Linux
root=any@gmx.de
mailhub=mail.gmx.net:587
rewriteDomain=gmx.net
hostname=gmx.net
FromLineOverride=YES
AuthUser=any@gmx.de
AuthPass=TopSecret
UseSTARTTLS=YES
TLS_CA_File=/etc/pki/tls/certs/ca-bundle.crt
''')
