#! /bin/bash -x
set -e
PATH=/usr/bin:/bin
BASE=/usr/share/form2linux
rm -f $BASE/doc/form2linux.md
for dir in base text doc; do
  rm -Rf $BASE/$dir/__pycache__
  rm -f $BASE/$dir/*
done
rm -Rf __pycache__/
rm -f *.py *.md
exit 0
